[project]
name = "api"
version = "0.1.0"
description = ""
authors = [
    {name = "tdang2180",email = "tdang2180@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "sqlmodel (>=0.0.42,<0.0.43)",
    "psycopg2-binary (>=2.9.13,<3.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]


[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
